## **TEHREEM ZUBAIR**
## **BYTEWISE FELLOWSHIP**
## **TASK 11**

---
## **INDEXING**

Indexing in NumPy allows for retrieving and modifying the elements of an array in a variety of ways. Here are descriptions and examples of basic indexing, boolean indexing, and fancy indexing.

---

### **BASIC INDEXING**
Basic indexing is similar to indexing in standard Python lists. You can use integers to access specific elements or slices to access a range of elements.

In [2]:
import numpy as np

In [3]:
# 1D array indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d[2]) 

# 2D array indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2]) 

# 3D array indexing
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])  

30
6
6


### **BOOLEAN INDEXING**
Boolean indexing is a way to select elements from an array using a boolean array (an array of True and False values) that matches the shape of the original array. This can be used to filter the array based on conditions.

In [4]:
# Boolean indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])  

# 2D array boolean indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[arr_2d > 5])  

[4 5]
[6 7 8 9]


### **FANCY INDEXING**
Fancy indexing is a way to index arrays using other arrays as indices. It allows you to select multiple elements or rows and columns simultaneously.

In [5]:
# Fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(arr[indices]) 

# 2D array fancy indexing
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
print(arr_2d[rows, cols]) 


[20 40 50]
[3 5 7]


---
## **SLICING**
- Slicing allows you to access a subset of elements from an array using the : operator.
- Syntax: array[start:end:step]
---
### **BASIC SLICING**
Basic slicing involves using the colon : operator to specify the start and end indices for the selection. It's similar to slicing lists in Python, but can be applied across multiple dimensions.



In [8]:
# 1D array slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) 

# 2D array slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0:2, 1:3]) 

# 3D array slicing
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[:, 1, :]) 

[20 30 40]
[[2 3]
 [5 6]]
[[3 4]
 [7 8]]


### **STEP SLICING**
NumPy allows us to select elements from an array with a specified step or stride. This is useful when we want to skip over elements in the array. 

In [9]:
# in 1D arrays
arr = np.array([10, 20, 30, 40, 50])

# Select every second element starting from index 0
print(arr[::2])  

# Select every second element starting from index 1
print(arr[1::2])  


[10 30 50]
[20 40]


In [10]:
# in 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select every second row and every second column
print(arr_2d[::2, ::2])

# Select every second row and every second column starting from row 1 and column 1
print(arr_2d[1::2, 1::2])

# Select every second row and every second column starting from row 0 and column 1
print(arr_2d[0::2, 1::2])

[[1 3]
 [7 9]]
[[5]]
[[2]
 [8]]


---
## **BROADCASTING**
- Broadcasting refers to how arrays with different shapes are treated during arithmetic operations. 
- The smaller array is "broadcasted" across the larger array so that they have compatible shapes. 
- This eliminates the need for explicit loops over array elements and makes code more readable and efficient.
---

**BROADCASTING RULES:**
- **Dimension Matching:** NumPy compares the dimensions of the two arrays from right to left.
- **Singleton Dimensions:** If the size of the dimension in one array is 1, it is stretched to match the size of the dimension in the other array.
- **Dimension Prepending:** If one array has fewer dimensions than the other, 1s are prepended to its shape until both shapes have the same number of dimensions.

### **1D AND 2D ARRAYS**

In [8]:
# 1D array
a = np.array([1, 2, 3])  
# 2D array 
b = np.array([[4, 5, 6], 
              [7, 8, 9]])

# Broadcasting 1D array to 2D array
c = a + b
print(c)

[[ 5  7  9]
 [ 8 10 12]]


### **SCALAR AND 2D ARRAY**

In [9]:
# Scalar 
a = 10
# 2D array
b = np.array([[1, 2, 3], 
              [4, 5, 6]])

# Broadcasting scalar to 2D array 
c = a + b
print(c)

[[11 12 13]
 [14 15 16]]


### **3D AND 2D ARRAYS**

In [4]:
# Broadcasting with higher dimensions
arr_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])
arr_2d = np.array([[10, 20, 30]])
print(arr_3d + arr_2d)

[[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]


---
## **ADVANCED ARRAY MANIPULATION**
---
### **TRANSPOSING ARRAYS**
Transposing arrays in NumPy involves swapping the axes of the array. This can be useful for various matrix operations, especially in linear algebra.

In [5]:
# Transposing a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.T) 

# Transposing a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.transpose(1, 0, 2))

[[1 4]
 [2 5]
 [3 6]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### **RESHAPING ARRAYS**
Reshaping arrays allows you to change the shape (number of dimensions) of an array without changing its data. This is useful when you need to prepare data for machine learning models or other computational tasks.

In [6]:
# Reshaping a 1D array to 2D
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)

# Reshaping a 2D array to 3D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_reshaped_3d = arr_2d.reshape(1, 2, 3)
print(arr_reshaped_3d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


### **STACKING ARRAYS**
Stacking arrays involves joining multiple arrays along a new or existing axis. This can be done using functions like np.vstack, np.hstack, np.dstack, and np.concatenate.


In [7]:
# Stacking arrays vertically
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_v = np.vstack((arr1, arr2))
print(stacked_v)

# Stacking arrays horizontally
stacked_h = np.hstack((arr1, arr2))
print(stacked_h)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


---
## **PROBLEMS**
---

### **INDEXING AND SLICING**
**1. Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).**

In [13]:
arr = np.array([[2, 5, 4, 7, 3],
               [3, 7, 9, 4, 2],
               [1, 6, 3, 8, 2],
               [1, 5, 3, 8, 5],
               [2, 6, 4, 7, 1]])

arr[1:4, 1:4]

array([[7, 9, 4],
       [6, 3, 8],
       [5, 3, 8]])

**2. From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.**

In [14]:
arr_3d = np.array([[[2, 3],[4, 6],[9, 3]],
                   [[5, 2],[2, 9],[7, 1]],
                   [[1, 2],[2, 4],[6, 7]],
                   [[5, 1],[6, 0],[7, 3]]])

arr_3d[:2, :, 1]

array([[3, 6, 3],
       [2, 9, 1]])

**3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].**

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
indices = [1, 3, 4, 7]
print(arr[indices]) 

[20 40 50 80]


**4. Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].**

In [21]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

rows = np.array([0, 2, 3])
cols = np.array([1, 3])
selected = arr_2d[rows[:, np.newaxis], cols]

print(selected)


[[ 2  4]
 [10 12]
 [14 16]]


**5. From a 1D array of random integers, extract all elements that are greater than 10.**

In [25]:
arr = np.random.randint(1, 50, size=100)

arr[arr>10]

array([27, 31, 25, 14, 34, 43, 36, 15, 44, 18, 19, 35, 24, 40, 43, 21, 21,
       43, 34, 36, 39, 31, 40, 22, 18, 16, 16, 26, 44, 16, 16, 20, 30, 42,
       41, 12, 34, 34, 34, 34, 31, 22, 37, 18, 31, 32, 20, 34, 47, 31, 37,
       48, 30, 14, 12, 45, 13, 33, 45, 16, 13, 40, 23, 28, 42, 12, 39, 48,
       29, 15, 34, 28, 28, 43, 31])

**6. Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.**

In [33]:
arr_2d = np.array([[16, 2, 3, 4, 5],
                  [12, 3, 4, 5, 7],
                  [4, 5, 62, 7, 8],
                  [2, 3, 6, 3, 93],
                  [15, 25, 7, 3, 29]])

arr_2d[arr_2d > 15] = 0

arr_2d

array([[ 0,  2,  3,  4,  5],
       [12,  3,  4,  5,  7],
       [ 4,  5,  0,  7,  8],
       [ 2,  3,  6,  3,  0],
       [15,  0,  7,  3,  0]])

### **BROADCASTING**

**1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).**

In [35]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 7],
                  [6, 8, 9],
                  [3, 7, 5]])

arr_1d = np.array([1, 2, 3])

arr_2d + arr_1d

array([[ 2,  4,  6],
       [ 5,  7, 10],
       [ 7, 10, 12],
       [ 4,  9,  8]])

**2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).**

In [36]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 7],
                  [6, 8, 9]])

arr_1d = np.array([1, 2, 3])

arr_2d * arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 21],
       [ 6, 16, 27]])

**3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.**

In [37]:
arr1 = np.array([[1], [2], [3]])

arr2 = np.array([[1, 2, 3, 4]])

arr1 + arr2

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

**4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.**

In [40]:
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 3, 6], [1, 9, 7, 5]],
                   [[1, 6, 5, 3], [0, 4, 6, 4], [1, 6, 3, 5]]])
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [2, 5, 8, 9]])

arr_3d + arr_2d

array([[[ 2,  4,  6,  8],
        [10, 12, 10, 14],
        [ 3, 14, 15, 14]],

       [[ 2,  8,  8,  7],
        [ 5, 10, 13, 12],
        [ 3, 11, 11, 14]]])

### **SOME MORE**

**1. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.**

In [43]:
arr_2d = np.array([[1, 2, 3, 4, 5, 6],
                   [7, 8, 9, 10, 11, 12],
                   [13, 14, 15, 16, 17, 18],
                   [19, 20, 21, 22, 23, 24],
                   [25, 26, 27, 28, 29, 30],
                   [31, 32, 33, 34, 35, 36]])

sliced_arr = arr_2d[::2, ::2]
print(sliced_arr)
arr_1d = [1, 2, 3]

sliced_arr + arr_1d

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


array([[ 2,  5,  8],
       [14, 17, 20],
       [26, 29, 32]])

**2. From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.**

In [45]:
arr_3d = np.array([[[2, 3],[4, 6],[9, 3]],
                   [[5, 2],[2, 9],[7, 1]],
                   [[1, 2],[2, 4],[6, 7]],
                   [[5, 1],[6, 0],[7, 3]]])

sliced_arr = arr_3d[:, 1:, :]
print(sliced_arr)
arr_2d = np.array([[1, 4], [4, 7]])

sliced_arr - arr_2d

[[[4 6]
  [9 3]]

 [[2 9]
  [7 1]]

 [[2 4]
  [6 7]]

 [[6 0]
  [7 3]]]


array([[[ 3,  2],
        [ 5, -4]],

       [[ 1,  5],
        [ 3, -6]],

       [[ 1,  0],
        [ 2,  0]],

       [[ 5, -4],
        [ 3, -4]]])

**3. Given a 2D array, extract the diagonal elements and create a 1D array.**

In [46]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extract diagonal elements as a 1D array
diagonal_elements = np.diag(arr_2d)

diagonal_elements

array([1, 5, 9])

**4. Use slicing to reverse the order of elements in each row of a 2D array.**

In [47]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[:, ::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

**5. Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.**

In [48]:
arr_3d = np.random.randint(0, 10, size=(4, 5, 6))

sub_array = arr_3d[:2, :3, :4]
add_array = np.array([1, 2, 3, 4])
sub_array + add_array

array([[[ 2,  6,  4,  4],
        [ 3,  8,  9, 10],
        [ 7,  2, 12,  6]],

       [[ 7,  7, 11,  9],
        [ 4,  3,  5, 11],
        [ 9,  2, 11, 10]]])

**6. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.**

In [52]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

first_two_columns = arr_2d[:, :2]

first_two_columns = np.sum(first_two_columns, axis = 1)

new_column = first_two_columns[:, np.newaxis]
result = np.concatenate((arr_2d, new_column), axis=1)
print(result)

[[ 1  2  3  3]
 [ 4  5  6  9]
 [ 7  8  9 15]]


**7. Create a 2D array and use broadcasting to multiply each column by a different scalar value.**

In [53]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

scalars = np.array([2, 0.5, 3, 1.5])

arr_2d * scalars[np.newaxis, :]

array([[ 2.,  1.,  9.,  6.],
       [10.,  3., 21., 12.],
       [18.,  5., 33., 18.]])

**8. From a 2D array, extract rows where the sum of elements is greater than a specified threshold, and replace these rows with a predefined row vector.**

In [54]:
import numpy as np

# Create a 2D array (5x4)
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16],
                   [17, 18, 19, 20]])

# Predefined row vector to replace selected rows
row_vector = np.array([0, 0, 0, 0])

# Calculate sum of elements along rows
row_sums = np.sum(arr_2d, axis=1)

# Identify rows where sum is greater than threshold
rows_to_replace = row_sums > 40

# Replace rows with predefined row vector
arr_2d[rows_to_replace] = row_vector
 
arr_2d


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**9. Extract the upper triangular part of a square 2D array (excluding the diagonal) and replace it with zeros.**

In [55]:
arr_2d = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# Extract the upper triangular part excluding the diagonal
upper_triangular = np.triu(arr_2d, k=1)

# Replace the upper triangular part with zeros
arr_2d[np.triu_indices(arr_2d.shape[0], k=1)] = 0

arr_2d


array([[ 1,  0,  0,  0,  0],
       [ 6,  7,  0,  0,  0],
       [11, 12, 13,  0,  0],
       [16, 17, 18, 19,  0],
       [21, 22, 23, 24, 25]])

**10. Simulate rolling three six-sided dice 1000 times and compute the sum of the dice values for each roll.**

In [56]:
# Simulate rolling three six-sided dice
dice_rolls = np.random.randint(1, 7, size=(10000, 3))

# Compute the sum of the dice values for each roll
dice_sums = np.sum(dice_rolls, axis=1)

print("First 10 sums of rolling three six-sided dice 1000 times:")
print(dice_sums[:10])


First 10 sums of rolling three six-sided dice 1000 times:
[11 10  9  9  9  7 12 10 11  7]


**11. From a 3D array of shape (4, 3, 2), calculate the Euclidean norm (magnitude) of each vector along the third axis.**

In [57]:
arr_3d = np.random.random((4, 3, 2))

# Calculate the Euclidean norm along the third axis
euclidean_norm = np.linalg.norm(arr_3d, axis=2)
euclidean_norm

array([[0.25144988, 0.48206779, 0.70531028],
       [0.72559839, 0.79332621, 1.12644687],
       [1.10345671, 0.49587196, 0.83191341],
       [1.33643413, 0.82260778, 1.15380914]])

**12. Generate a 2D array of shape (5, 5) where each element is the result of a function applied to its indices (e.g., element at (i, j) = i * j).**

In [58]:
def func(i, j):
    return i * j

# Generate a 2D array of shape (5, 5) using the function
arr_2d = np.fromfunction(func, (5, 5), dtype=int)

arr_2d

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])