## **TEHREEM ZUBAIR**
## **TASK 10**
## **BYTEWISE FELLOWSHIP**

---

## **What is numpy?**
- Most popular and commonly used library in python.
- Stands for Numerical Python.
- If we take a look at the formal definition of numpy it states that:
> It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays. 

In simple words numpy provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures

---
## **Why numpy?**
The basic question question that arises is that why can't we just use lists for storing of the data. What are the key features that numoy provide that makes it necessary for data science and machine learning.
- The underlying functionallities of numpy are written in C which is really fast.
- On the contrary if we are using lists operations will be much more slower. 
- The basic opearion behind the increased speed is the vectorization via broadcasting that includes avoiding any kind of loops in the code.
- NumPy extends (and often replaces) Python's built-in features with highly-optimized code for numerical operations.



**Below is the complete guide of everything we need to learn about numpy. Let's get started!**

In [1]:
# importing numpy
import numpy as np

# check the version 
print(np.__version__)

1.26.4


---
## **DATA TYPES AND ATTRIBUTES**
An important thing to remember is that numpy main datatype is ndarray (n-dimensional array). This means that an operation you do on one array will work on the other.
Let's create some different dimension arrays for a better understanding.

In [2]:
# 1D array (vector)
arr1 = np.array([1, 2, 3])


# 2D array (matrix)
arr2 = np.array([[3, 5, 8,],
                 [3.0, 5.6, 5]])

# 3D array (matrix)
arr3 = np.array([[[1, 2, 4],
                 [5, 6, 8],
                 [7.0, 5.5, 4.7]],
                 [[5.5, 6.0, 7.5],
                  [3, 4, 5],
                  [6, 4, 2]]])

In [8]:
# Checking shapes of array
print("ARRAY 1: ", arr1.shape)    # result would be number of elements in vector
print("ARRAY 2: ", arr2.shape)    # result will be rows and columns in matrix
print("ARRAY 3: ", arr3.shape)    # will show number of subarrays and rows and column in each subarray

ARRAY 1:  (3,)
ARRAY 2:  (2, 3)
ARRAY 3:  (2, 3, 3)


In [9]:
# Checking the dimension
print("ARRAY 1: ", arr1.ndim)   # 1D 
print("ARRAY 2: ", arr2.ndim)   # 2D
print("ARRAY 3: ", arr3.ndim)   # 3D

ARRAY 1:  1
ARRAY 2:  2
ARRAY 3:  3


In [10]:
# Checking datatype 
print("ARRAY 1: ", arr1.dtype)   # 1D 
print("ARRAY 2: ", arr2.dtype)   # 2D
print("ARRAY 3: ", arr3.dtype)   # 3D

ARRAY 1:  int64
ARRAY 2:  float64
ARRAY 3:  float64


In [11]:
# Checking size ( number of total elements in the array)
print("ARRAY 1: ", arr1.size)    
print("ARRAY 2: ", arr2.size)   
print("ARRAY 3: ", arr3.size)

ARRAY 1:  3
ARRAY 2:  6
ARRAY 3:  18


In [15]:
# Printing the arrays
print("ARRAY 1: \n", arr1)
print("\n ARRAY 2: \n", arr2)
print("\n ARRAY 3: \n", arr3)

ARRAY 1: 
 [1 2 3]

 ARRAY 2: 
 [[3.  5.  8. ]
 [3.  5.6 5. ]]

 ARRAY 3: 
 [[[1.  2.  4. ]
  [5.  6.  8. ]
  [7.  5.5 4.7]]

 [[5.5 6.  7. ]
  [3.  4.  5. ]
  [6.  4.  2. ]]]


---
## **ARRAY CREATION**
NumPy offers several methods to create arrays, catering to different needs and scenarios. Here are some commonly used methods:

In [16]:
# from lists or tuples
arr = np.array([1, 2, 3])
(arr, arr.dtype)

(array([1, 2, 3]), dtype('int64'))

In [22]:
# predefined ranges and patterns
# arange -> 0 is lower limit , 10 is upper limit, 2 is the even gap between elements
arr = np.arange(0, 10, 3)
print(arr)

# linspace -> Generates an array with a specified number of evenly spaced values between a start and end point
arr = np.linspace(0, 1, 5) 
print(arr)

[0 3 6 9]
[0.   0.25 0.5  0.75 1.  ]


In [23]:
# creating arrays of zeros , ones and constants
# np.zeros(): Creates an array filled with zeros.
arr = np.zeros((2, 3)) 
print(arr)

# np.ones(): Creates an array filled with one
arr = np.ones((2, 3))
print(arr)

# np.full(): Creates an array filled with a specified value.
arr = np.full((2, 3), 7)  # Output: [[7, 7, 7], [7, 7, 7]]
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


In [27]:
# identity matrix
# np.eye(): Creates a 2D identity matrix.
arr = np.eye(3)  # Output: [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]
print(arr)

# np.diag(): Extracts or creates a diagonal array.
arr = np.diag([1, 2, 3])  # Output: [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [28]:
# Randomly generated arrays
# np.random.rand(): Creates an array of the given shape with random samples from a uniform distribution over [0, 1).
arr = np.random.rand(2, 3)
print(arr)

[[0.4896481  0.23813819 0.2528627 ]
 [0.30646338 0.41282073 0.03546336]]


In [29]:
# np.random.randn(): Creates an array of the given shape with samples from the standard normal distribution.
arr = np.random.randn(2, 3)
print(arr)

[[ 0.39726718 -0.01342591  1.45600641]
 [-0.08229919  2.00269167  0.21673995]]


In [30]:
# np.random.randint(): Creates an array with random integers from a specified range.
arr = np.random.randint(0, 10, (2, 3))
arr

array([[1, 4, 0],
       [2, 7, 5]])

---
## **VIEWING ARRAYS AND MARTIX**


In [35]:
arr1 = np.array([1, 2, 3, 5])

arr2 = np.array([[3, 5, 8,],
                 [3.0, 5.6, 5]])

arr3 = np.array([[[1, 2, 4],
                 [5, 6, 8],
                 [7.0, 5.5, 4.7]],
                 [[5.5, 6.0, 7.5],
                  [3, 4, 5],
                  [6, 4, 2]]])

### **VIEWING ARRAYS THROUGH INDEXING**

In [36]:
arr1[0]

1

In [37]:
arr2[1]

array([3. , 5.6, 5. ])

In [38]:
arr3[0]

array([[1. , 2. , 4. ],
       [5. , 6. , 8. ],
       [7. , 5.5, 4.7]])

In [42]:
arr2[1, 1]  # 2nd entry of second row

5.6

In [45]:
arr3[1, 2, 2]

2.0

In [46]:
# Get the first 2 values of the first 2 rows of both arrays
arr3[:2, :2, :2]

array([[[1. , 2. ],
        [5. , 6. ]],

       [[5.5, 6. ],
        [3. , 4. ]]])

---
## **BASIC OPERATIONS**

### 1. ARITHEMATIC OPERATIONS

In [59]:
# 1D Array
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

# Arithmetic operations
add1 = a1 + b1  
sub1 = a1 - b1  
mul1 = a1 * b1  
div1 = a1 / b1  
pow1 = a1 ** 2  
print(add1, sub1, mul1, div1, pow1)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [1 4 9]


In [65]:
# 2D Array
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])

# Arithmetic operations
add2 = a2 + b2  
sub2 = a2 - b2  
mul2 = a2 * b2  
div2 = a2 / b2 
pow2 = a2 ** 2  
print("ADDITION: \n", add2,"\nSUBTRACTION: \n", sub2,"\nMULTIPLICATION: \n", mul2,"\nDIVISION: \n", div2,"\nPOWER: \n", pow2)

ADDITION: 
 [[ 6  8]
 [10 12]] 
SUBTRACTION: 
 [[-4 -4]
 [-4 -4]] 
MULTIPLICATION: 
 [[ 5 12]
 [21 32]] 
DIVISION: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]] 
POWER: 
 [[ 1  4]
 [ 9 16]]


In [69]:
# 3D Array
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b3 = np.array([[[1, 1], [1, 1]], [[2, 2], [2, 2]]])

# Arithmetic operations
add3 = a3 + b3  
sub3 = a3 - b3  
mul3 = a3 * b3  
div3 = a3 / b3  
pow3 = a3 ** 2 
print("ADDITION: \n", add3,"\n\nSUBTRACTION: \n", sub3,"\n\nMULTIPLICATION: \n", mul3,"\n\nDIVISION: \n", div3,"\n\nPOWER: \n", pow3)

ADDITION: 
 [[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]] 

SUBTRACTION: 
 [[[0 1]
  [2 3]]

 [[3 4]
  [5 6]]] 

MULTIPLICATION: 
 [[[ 1  2]
  [ 3  4]]

 [[10 12]
  [14 16]]] 

DIVISION: 
 [[[1.  2. ]
  [3.  4. ]]

 [[2.5 3. ]
  [3.5 4. ]]] 

POWER: 
 [[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


### 2. EXPONENTIAL AND LOGARITHMIC FUNCTIONS

In [72]:
exp1 = np.exp(a1) 
log1 = np.log(a1) 

exp2 = np.exp(a2)  
log2 = np.log(a2)  

exp3 = np.exp(a3)  
log3 = np.log(a3)  

In [73]:
print("EXPONENTIAL FUNCTION ON 2D ARRAY: ", exp2)
print("\n\nLOGARITHMIC FUNCTION ON 2D ARRAY: ", log2)

EXPONENTIAL FUNCTION ON 2D ARRAY:  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


LOGARITHMIC FUNCTION ON 2D ARRAY:  [[0.         0.69314718]
 [1.09861229 1.38629436]]


### 3. DOT PRODUCT

In [75]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
np.dot(a1, b1)  # Output: 32

32

In [77]:
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b3 = np.array([[[1, 1], [1, 1]], [[2, 2], [2, 2]]])
np.dot(a3, b3)  # Not directly applicable; needs reshaping or specific axes


array([[[[ 3,  3],
         [ 6,  6]],

        [[ 7,  7],
         [14, 14]]],


       [[[11, 11],
         [22, 22]],

        [[15, 15],
         [30, 30]]]])

### 4. AGGREGATION


In [79]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

# sum of all values
sum1 = np.sum(a1)  
# mean value of the array
mean1 = np.mean(a1)
# standard deviation
std1 = np.std(a1)  
# variance
var1 = np.var(a1)
# minimum values from array
min1 = np.min(a1) 
# maximum values from array
max1 = np.max(a1) 
argmin1 = np.argmin(a1) 
argmax1 = np.argmax(a1)  

print("\nSUM OF ALL VALUES : ", sum1, "\n\nMEAN: \n", mean1, "\n\nSTANDARD DEVIATION: \n", std1, "\n\nVARIANCE: \n", var1, "\n\nMINIMUM VALUE: \n", min1, "\n\nMAXIMUM VALUE: \n", max1)


SUM OF ALL VALUES :  6 

MEAN: 
 2.0 

STANDARD DEVIATION: 
 0.816496580927726 

VARIANCE: 
 0.6666666666666666 

MINIMUM VALUE: 
 1 

MAXIMUM VALUE: 
 3


---
# **PROBLEMS**
1. **Create a 1D NumPy array containing the integers from 0 to 9.**

In [81]:
# PROBLEM 1
arr = np.array([0, 7, 5, 3, 2, 8, 6])
arr


array([0, 7, 5, 3, 2, 8, 6])

2. **Create a 2D NumPy array (3x3) containing random integers between 1 and 20.**

In [82]:
# PROBLEM 2
arr = np.random.randint(1, 20, (3, 3))
arr

array([[ 3,  2,  1],
       [ 3, 15,  3],
       [14, 10,  1]])

3. **Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.**

In [80]:
# PROBLEM 3
arr = np.ones((2, 3, 4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

**4. Add two 1D arrays element-wise.**

In [83]:
arr1 = np.array([2, 3, 6, 1, 7, 4])
arr2 = np.array([5, 2, 3, 7, 4, 7])
arr1 + arr2

array([ 7,  5,  9,  8, 11, 11])

**5. Multiply two 2D arrays element-wise.**

In [85]:
arr1 = np.array([[2, 3, 6], 
                [1, 7, 4]])
arr2 = np.array([[5, 2, 3], 
                [7, 4, 7]])

arr1 * arr2

array([[10,  6, 18],
       [ 7, 28, 28]])

**6. Calculate the dot product of two matrices.**

In [87]:
arr1 = np.array([[2, 3, 6],
                 [1, 7, 4]])

arr2 = np.array([[5, 2],
                 [3, 7],
                 [4, 7]])

result = np.dot(arr1, arr2)
print(result)


[[43 67]
 [42 79]]


**7. Calculate the mean, median, and standard deviation of a 1D array.**

In [91]:
arr = np.array([1, 4, 6, 3, 8, 3])
(np.mean(arr), np.median(arr), np.std(arr))

(4.166666666666667, 3.5, 2.266911751455907)

**8. Find the maximum and minimum values in a 2D array.**

In [92]:
arr1 = np.array([[2, 3, 6],
                 [1, 7, 4]])

(np.max(arr1), np.min(arr1))

(7, 1)

**9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.**

In [94]:
# Generate an array of 1000 random numbers from a normal distribution
mean = 0
std_dev = 1
random_numbers = np.random.normal(mean, std_dev, 1000)

# print first ten numbers 
print(random_numbers[:10])

[ 0.34585746 -1.12138931  0.38541183 -0.46434678 -0.11979681 -0.18080128
 -1.20079214  1.16704706 -0.93190759  0.05289611]


**10. Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.**

In [95]:
np.random.randint(10, 51, size=(5, 5))

array([[26, 43, 33, 48, 46],
       [31, 33, 48, 19, 20],
       [30, 39, 41, 15, 23],
       [20, 32, 50, 23, 21],
       [36, 11, 33, 35, 11]])

**11. Calculate the cumulative sum of a 1D array.**

In [98]:
a1 = np.array([1, 2, 3])

# sum of all values
np.sum(a1)

6

**12. Compute the correlation coefficient matrix of a 2D array.**

In [100]:
# first randomly generate a 2D matrix
data = np.random.rand(5, 4)

np.corrcoef(data, rowvar=False)  # rowvar=False for columns as variables


array([[ 1.        , -0.3800264 , -0.45558881, -0.76577561],
       [-0.3800264 ,  1.        , -0.28296812, -0.19260697],
       [-0.45558881, -0.28296812,  1.        ,  0.34236591],
       [-0.76577561, -0.19260697,  0.34236591,  1.        ]])

**13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.**

In [109]:
die_rolled  = np.random.randint(1, 7, size = 1000)

# now count frequency of each outcome using bincount

freq = np.bincount(die_rolled)[1:]

# Print the frequency of each outcome
for outcome, count in enumerate(freq, start=1):
    print(f"Outcome {outcome}: {count} times")

# Optionally, you can also print the total number of rolls to verify (should be 1000)
print(f"Total Rolls: {len(die_rolled)}")

Outcome 1: 177 times
Outcome 2: 163 times
Outcome 3: 154 times
Outcome 4: 164 times
Outcome 5: 170 times
Outcome 6: 172 times
Total Rolls: 1000


In [2]:
import numpy as np

---
## **SOME MORE PROBLEMS**

**1. Generate an array of 500 random numbers from a uniform distribution between -1 and 1.**

In [6]:
arr = np.random.uniform(-1, 1, (500))

print(arr[:10])

[ 0.13571731 -0.7629266   0.29878013 -0.77555082 -0.1003745  -0.5534041
 -0.17844984  0.15219693  0.79910891 -0.69214295]


**2. Create a 2D array of shapes (6, 6) with random integers from a uniform distribution between 0 and 100.**

In [7]:
np.random.randint(0, 101, (6, 6))

array([[ 93,  95,  43,  94,  97,  94],
       [ 25,  14,  56,  98,  30,  77],
       [ 82,  25,  50,  60,  96,  49],
       [ 12,  83,  85,  48,  86,  83],
       [ 68,  37,  45,  34, 100,  88],
       [100,  28,  98,  11,   5,  28]])

**3. Calculate the cumulative product of a 1D array.**

In [8]:
arr = np.array([2, 4, 6, 3, 4])
np.product(arr)

576

**4. Compute the covariance matrix of a 2D array.**

In [12]:
data = np.array([[2.5, 2.4, 3.6],
                 [0.5, 0.7, 1.2],
                 [2.2, 2.9, 3.1],
                 [1.9, 2.2, 3.3],
                 [3.1, 3.0, 4.1]])

np.cov(data)

array([[0.44333333, 0.225     , 0.19333333, 0.47166667, 0.405     ],
       [0.225     , 0.13      , 0.145     , 0.265     , 0.205     ],
       [0.19333333, 0.145     , 0.22333333, 0.28166667, 0.175     ],
       [0.47166667, 0.265     , 0.28166667, 0.54333333, 0.43      ],
       [0.405     , 0.205     , 0.175     , 0.43      , 0.37      ]])

**5. Simulate tossing a fair coin 10000 times and count the frequency of heads and tails.**

In [26]:
toss = np.random.randint(0, 2, 10000)

freq = np.bincount(toss)[0:]

# Print the frequency of each outcome
for outcome, count in enumerate(freq, start=0):
    if(outcome == 0):
        print(f"Head: {count} times")
    else:
        print(f"Tail: {count} times")

Head: 5013 times
Tail: 4987 times


In [31]:
outcomes = ['head', 'tail']

tosses = np.random.choice(outcomes, size = 10000, p = [0.5, 0.5])

# Count the frequency of each outcome
heads_count = np.sum(tosses == 'head')
tails_count = np.sum(tosses == 'tail')

# Print the results
print(f"Heads: {heads_count}")
print(f"Tails: {tails_count}")


Heads: 5039
Tails: 4961


**6. Create a diagonal matrix from a 1D array of integers.**

In [32]:
arr = np.array([0, 8, 6, 4, 1])

np.diag(arr)

array([[0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1]])

**7. Reshape a 1D array into a 2D array of shape (4, 3).**

In [34]:
arr = ([1, 2, 8, 7, 4, 3])

np.reshape(arr, (2, 3))

array([[1, 2, 8],
       [7, 4, 3]])

**8. Transpose a 2D array of shape (2, 3) into a (3, 2) array.**

In [35]:
matrix = np.array([[1, 3, 4],
                   [3, 8, 9]])

np.reshape(matrix, (3, 2))

array([[1, 3],
       [4, 3],
       [8, 9]])

**9. Normalize (scale between 0 and 1) a 1D array of random numbers.**

In [3]:
arr = np.array([5, 4, 2, 8, 9, 2, 6])

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

np.round(normalized, 2)

array([0.43, 0.29, 0.  , 0.86, 1.  , 0.  , 0.57])

**10. Calculate the eigenvalues and eigenvectors of a symmetric 3x3 matrix.**

In [4]:
# Create a symmetric 3x3 matrix
matrix = np.array([[4, 1, 1],
                   [1, 3, 0],
                   [1, 0, 2]])

# Ensure the matrix is symmetric
assert np.allclose(matrix, matrix.T), "The matrix is not symmetric!"

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[4.87938524 1.46791111 2.65270364]

Eigenvectors:
[[-0.84402963 -0.44909879  0.29312841]
 [-0.44909879  0.29312841 -0.84402963]
 [-0.29312841  0.84402963  0.44909879]]


**11. Simulate drawing 500 samples from a Poisson distribution with parameter lambda=3.**

In [5]:
lambda_param = 3
samples = 500

poisson_samples = np.random.poisson(lambda_param, samples)
print("First 10 samples from the Poisson distribution:")
print(poisson_samples[:10])


First 10 samples from the Poisson distribution:
[5 2 2 1 2 2 5 5 2 1]


**12. Simulate drawing 200 samples from a uniform distribution between 0 and 1.**

In [6]:
samples = 200

uniform_samples = np.random.uniform(0, 1, samples)
print("First 10 samples from the uniform distribution:")
print(uniform_samples[:10])


First 10 samples from the uniform distribution:
[0.9394684  0.29084827 0.3160471  0.27956093 0.45208647 0.20491293
 0.61213415 0.55107575 0.87630999 0.78176401]


**13. Generate a 2D array (5x5) of random numbers from a standard normal distribution.
python.**

In [10]:
normal_samples_2d = np.random.normal(0, 1, (5, 5))
print(np.round(normal_samples_2d, 2))

[[-0.21  0.12 -2.06 -0.85 -1.17]
 [-2.09  0.26  0.4   0.34 -1.41]
 [ 0.05 -2.09 -1.45 -0.17 -0.68]
 [-1.41  1.24 -2.14 -1.73 -1.31]
 [-2.09 -1.7  -1.61  0.32 -1.17]]


**14. Simulate drawing 100 samples from a normal distribution with mean 5 and standard deviation.**

In [11]:
mean = 5
std_dev = 2
samples = 100

normal_samples = np.random.normal(mean, std_dev, samples)
print(normal_samples[:10])


[3.05126487 8.18335011 1.75467683 3.28468151 3.4193831  4.4605475
 1.96440275 4.69900827 5.08389865 3.17485959]


**15. Generate a 3x3 matrix of random numbers from a uniform distribution between -5 and 5.**

In [12]:
uniform_matrix = np.random.uniform(-5, 5, (3, 3))
print(uniform_matrix)


[[ 0.63694777  0.79737612  4.6536788 ]
 [-2.63518891  3.86399793  2.34911411]
 [-1.01991931  4.08083652  2.27866913]]
